#!/usr/bin/perl
use strict;
use LWP::UserAgent;

my $uri     = shift || "http://localhost:9999/";
my $message = shift || "This is a test commit with github-hook-googlecode.";

my $res = LWP::UserAgent->new->post($uri, { payload => << "JSON" });
{
  "before": "5aef35982fb2d34e9d9d4502f6ede1072793222d",
  "repository": {
    "url": "http://github.com/defunkt/github",
    "name": "github",
    "description": "You're lookin' at it.",
    "watchers": 5,
    "forks": 2,
    "private": 1,
    "owner": {
      "email": "john\@example.com",
      "name": "defunkt"
    }
  },
  "commits": [
    {
      "id": "41a212ee83ca127e3c8cf465891ab7216a705f59",
      "url": "http://github.com/defunkt/github/commit/41a212ee83ca127e3c8cf465891ab7216a705f59",
      "author": {
        "email": "john\@example.com",
        "name": "John Smigh"
      },
      "message": "$message",
      "timestamp": "2008-02-15T14:57:17-08:00",
      "added": ["filepath.rb"]
    }
  ],
  "after": "de8251ff97ee194a289832576287d6f8ad74e3d0",
  "ref": "refs/heads/master"
}
JSON

warn $res->content;
